server:
  port: 8081
spring:
  application:
    name: car
security:
  oauth2:
    resource:
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAk0vZKkCiYALeCzs05Iily8i9ivYEMiGYBN5ESfA5LCgXkp4k1C8r+P/WPlXUGZLjklXzUPPHJ+a7T+pCaX6aKbRtIAuSGKn8f2YnnHp8t0SaHGj5SW6OueVif0mD+GKXqYR8wnH+u4MoezsBcRoHQCZR2ZrgRqjrOYtpOnTo1oaWZdPlGlaSjDCkj6ruY1XIBuui2SYLBq0AMtnTT/wwPDuEVy+nzRgiGwDnbSvudoNAV0u9DeEYG7M+K3fzmGXQsL6XDW8Y+VnbP7l40A5ZHwD0tK+dUx41v5kgYGCGZpow3BYQryKNbs3hMWFEHcNrjhLI5sVSm2MHao8LFncBqQIDAQAB
          -----END PUBLIC KEY-----