server:
  port: 8081
spring:
  application:
    name: car
security:
  oauth2:
    resource:
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCmYmv8V96njvMDtjHd1gOVYGXz/0JiV/+rMs4AFUof7n5S/LGDcWfVmfa9nZOqdIkRCZYdFlgxq0MY07k+xcBX1AvjUDL0R5UOQBOjgKf4s5SWl2enLqeqL6UYvCikboQgf3FHw+TWZkJYwjOygPRBad4ojQsgp+i/Glo02bljewIDAQAB
          -----END PUBLIC KEY-----