version: '3'

services:
    kafka:
        image: wurstmeister/kafka:1.1.0
        ports:
            - 9092:9092
        environment:
            - KAFKA_ADVERTISED_PORT=9092
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_ADVERTISED_HOST_NAME=localhost
        depends_on:
            - zookeeper
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - 2181:2181
